name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    name: Clippy (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - name: Android
            os: ubuntu-latest
            target: aarch64-linux-android

    steps:
      - uses: actions/checkout@v7

      - name: Check path changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            code_changed:
              - 'src/**'
              - 'Cargo.toml'
              - 'Cargo.lock'

      - name: Install Rust
        if: steps.filter.outputs.code_changed == 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: ${{ matrix.target }}

      - name: Run Clippy
        if: steps.filter.outputs.code_changed == 'true'
        run: cargo clippy --target ${{ matrix.target }} -- -D warnings
